-- to create the table the first time --
DROP TABLE users IF EXISTS;
CREATE TABLE users (
   iduser INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_name VARCHAR (45) NOT NULL,
   birthdate TIMESTAMP NOT NULL,
   residence_country VARCHAR (45) NOT NULL,
   phone_number VARCHAR (16),
   gender VARCHAR (6)  
);

-- Example to use in the application to populate the table the first time with French adult only --
INSERT INTO users(user_name, birthdate, residence_country, phone_number, gender) VALUES('Dupont','1980-03-01 20:10:00','French','0632657800','Male');
INSERT INTO users(user_name, birthdate, residence_country, phone_number, gender) VALUES('Durant','1990-11-08 10:08:08','French','0492921010','Female');

-- To check the insertion --
SELECT * FROM users;

-- Example of deletion of a row --
DELETE FROM users WHERE iduser = 1;